[package]
name = "aeth-task"
description = "Tasking system for aeth-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[features]
future-ready-wait = ["dep:aeth-event", "dep:indexed-bitmap", "dep:lives"]
default = ["future-ready-wait"]

[dependencies]
futures.workspace = true
anyhow.workspace = true
tokio.workspace = true
core_affinity.workspace = true
thread-priority.workspace = true
rand.workspace = true
aeth-event = { workspace = true, optional = true }
indexed-bitmap = { workspace = true, optional = true}
lives = { workspace = true, optional = true }

[dev-dependencies]